import sys
sys.path.insert(0, '/tmp/round-3')
from sim import greedy_seq
from sympy import primefactors
from collections import Counter

def detect_period_from_start(seq, maxT=None):
    diffs = [seq[i+1]-seq[i] for i in range(len(seq)-1)]
    N = len(diffs)
    if maxT is None: maxT = min(N//3, 6500)
    for T in range(1, maxT+1):
        ok = all(diffs[k] == diffs[k+T] for k in range(N-T))
        if ok and N-T >= T:
            return T, sum(diffs[:T]), diffs[:T]
    return None

def primitive_period(w):
    """Return (u, k) with w=u^k, u primitive, k maximal."""
    T = len(w)
    for m in range(1, T+1):
        if T % m == 0:
            u = w[:m]
            if all(w[i]==u[i % m] for i in range(T)):
                k = T // m
                # check u is primitive
                pprim = primitive_period(u) if m > 1 else (u, 1)
                if m == 1 or pprim[1] == 1:
                    return u, k
    return w, 1

def is_substitution_invariant(w):
    """Is w = sigma(w) for a nontrivial letter->word substitution sigma (uniform length k | T)?
    Try each k | T: group w into blocks of size k starting at offset 0; check if there's a
    consistent sigma: letter_i -> block, with sigma a function on the alphabet."""
    T = len(w)
    res = []
    for k in range(2, T+1):
        if T % k != 0: continue
        # sigma maps each letter to a length-k word. w = sigma(w[0]) sigma(w[1]) ... sigma(w[T-1])
        # but sigma(w[i]) has length k, so concatenation has length k*T. For w=sigma(w) we need |w|=k*|w| => k=1.
        # So uniform substitution fixed-point requires k=1. Skip.
        pass
    # Non-uniform: sigma maps each letter to a word of length >=1; w = sigma(w[0..T-1]) concatenated.
    # Length: sum_i |sigma(w_i)| = T. If sigma is defined on the alphabet A (size |A|), and each letter
    # maps to a word of length L_a, then for w (period T) we need the multiset of letters in w to satisfy
    # sum_{a in A} (count_a * L_a) = T, and the actual sigma(a) words concatenate (in the order of w's letters) to w.
    # This is a strong constraint. Test: for each divisor structure, try to find such sigma.
    alpha = sorted(set(w))
    cnt = Counter(w)
    T = len(w)
    # brute: for each assignment of lengths L_a >= 1 with sum cnt[a]*L_a = T, check consistency
    # (too many for large alpha; only test small-alpha cases)
    if len(alpha) > 6:
        return "skip (alphabet too large)"
    # Try: does there exist sigma with sigma(a) = some contiguous subword, consistent?
    # Simpler test: is w a fixed point of a CYCLIC PERMUTATION of its letters?
    # sigma = cyclic shift of alphabet: sigma(alpha[i]) = alpha[(i+1) % len(alpha)] (length-1).
    # Then sigma^len(alpha) = id, and w = sigma(w) means w is invariant under renaming letters cyclically.
    n = len(alpha)
    inv = {c:i for i,c in enumerate(alpha)}
    for shift in range(1, n):
        sigma = {alpha[i]: alpha[(i+shift) % n] for i in range(n)}
        if all(sigma[w[i]] == w[i] for i in range(T)):  # length-1, so sigma(w)=w letterwise => w constant. nope
            pass
    # length-1 substitution = letter permutation; w=sigma(w) means w is fixed as a WORD under letter perm.
    # That requires w_i = sigma(w_i) for all i, i.e., each letter is a fixed point of sigma.
    # Only the identity fixes all appearing letters. So nontrivial length-1 sub only if... w has repeated structure.
    # The real question: is w generated by sigma applied to a SHORTER seed? w = sigma^m(seed)?
    return res

for a1 in [15, 35, 77, 91, 105, 143, 1309, 2085]:
    M1 = 1
    for p in primefactors(a1): M1 *= p
    N = 14000 if a1 in (1309,2085) else 4000
    seq = greedy_seq(a1, N)
    res = detect_period_from_start(seq)
    if res is None:
        print(f"a1={a1}: no period"); continue
    T, L, w = res
    u, k = primitive_period(w)
    alpha = sorted(set(w))
    print(f"a1={a1} T={T}: primitive period |u|={len(u)} (k={k}); alphabet size={len(alpha)}")
    # Show the actual primitive word for small cases
    if len(u) <= 60:
        print(f"   u = {u}")
    # check: is u a power of a single letter? (degenerate)
    print(f"   distinct letters in u: {sorted(set(u))}")
